version: '3'

services:
  proxy:
    image: apiservicoanuncio-nginx
    build:
      context: .
    ports:
      - "2000:80"
    depends_on:
       - apiservicoanuncio01
       - apiservicoanuncio02
       - apiservicoanuncio03
    networks:
      - apiservicoanuncio-network

  apiservicoanuncio01:
    image: apiservicoanuncio-sdk-2-2
    ports:
      - "20001:80"
    networks:
      - apiservicoanuncio-network

  apiservicoanuncio02:
    image: apiservicoanuncio-sdk-2-2
    ports:
      - "20002:80"
    networks:
      - apiservicoanuncio-network

  apiservicoanuncio03:
    image: apiservicoanuncio-sdk-2-2
    ports:
      - "20003:80"
    networks:
      - apiservicoanuncio-network

networks:
  apiservicoanuncio-network:
    driver: bridge